

page_server_url = "localhost:3000"
email           = "your@email.com"        #your@email.com
password        = "your_github_password"  #ENV[GITHUB_PASSWORD]
repo_url        = "your_github_url"       #github/mskim

task :push do
  system("git push")
end

task :pull do
  system("git pull")
end

# call page_server to process the repos content
task :pdf do
  # git remote show origin
  "curl #{page_server_url}/pdf/?repos=#{repo_url}?email=#{email}?password=#{password}"
end

task :print do
  "curl #{page_server_url}/print/?repos=#{repo_url}?email=#{email}?password=#{password}"
end

# for buying print_ready_pdf 
task :print_ready_pdf do
  "curl #{page_server_url}/print_ready_pdf/?repos=#{repo_url}?email=#{email}?password=#{password}"
end