
source_files = FileList["**/*.rb"]

task :default => :pdf

task :pdf => source_files.ext(".pdf")
rule ".pdf" => ".rb" do |t|
  # script = File.open(t.source){|f| f.read}
  # system(" echo '#{script}' | /Applications/rjob.app/Contents/MacOS/rjob")
  system("/Applications/rjob.app/Contents/MacOS/rjob #{pwd}/#{t.source}")
end
