require File.dirname(__FILE__) + "/article/story"
require File.dirname(__FILE__) + "/article/story_box"
require File.dirname(__FILE__) + "/article/chapter"
require File.dirname(__FILE__) + "/article/chapter"
require File.dirname(__FILE__) + "/article/magazine_article"
require File.dirname(__FILE__) + "/article/news_article"
