require File.dirname(__FILE__) + '/text/font'
require File.dirname(__FILE__) + '/text/paragraph'
require File.dirname(__FILE__) + '/text/text_column'
require File.dirname(__FILE__) + '/text/heading'
require File.dirname(__FILE__) + '/text/story_box'