require File.dirname(__FILE__) + '/text/font'
require File.dirname(__FILE__) + '/text/style_service'
# require File.dirname(__FILE__) + '/text/text_layout'
require File.dirname(__FILE__) + '/text/paragraph'
require File.dirname(__FILE__) + '/text/paragraph_j'
# require File.dirname(__FILE__) + '/text/rich_paragraph'
require File.dirname(__FILE__) + '/text/text_column'
require File.dirname(__FILE__) + '/text/heading'
